### ISSUE TITLE
Error in Installation

### ISSUE THREAD

**Issue by lordim** [oxpig/ANARCI#16]
I have cloned the repository for ANARCI and tried to install it, but got the following error:

![image](https://user-images.githubusercontent.com/35266817/123185594-48e94f80-d464-11eb-9f15-e85cfba1414e.png)

I have no idea what could have gone wrong in my installation process since all I've done was "python3 setup.py install --user"

Thanks!

**Comment by gciaberi** [comment]
Do you have HMMER installed on your computer ? 
Although the traceback shows an error with the muscle program (which is included in ANARCI I believe), it also shows it cannot find commands from HMMER (hmmbuild and hmmpress). If that doesn't work, try installing muscle too.

**Comment by broncio123** [comment]
Was this ever resolved? @lordim 
I know it's been a while ago but if so, please comment the solution and close the issue. Otherwise, let us know to look into it.

**Comment by awesome-crab** [comment]
First of all my working environment:
Docker image
OS Ubuntu 20.04
Python version 3.8
Hmmer version 3.3+
biopython installed

On docker image ubuntu you are root, so I installed with: python3 setup.py install.

Had the same issue. 
Installed HMMER: apt install hmmer

Next ERROR:
`Traceback (most recent call last):
  File "./FormatAlignments.py", line 480, in <module>
    main()
  File "./FormatAlignments.py", line 454, in main
    jalignments = format_j_genes(jalignments)
  File "./FormatAlignments.py", line 183, in format_j_genes
    aligned = read_fasta( al_filename )
  File "./FormatAlignments.py", line 127, in read_fasta
    handle = open(filename, "r")
FileNotFoundError: [Errno 2] No such file or directory: './muscle_alignments/all_js_aligned.fasta'
Alignment input open failed.
   couldn't open ./curated_alignments/ALL.stockholm for reading

Error: File existence/permissions problem in trying to open HMM file ./HMMs/ALL.hmm.
HMM file ./HMMs/ALL.hmm not found (nor an .h3m binary of it)


Traceback (most recent call last):
  File "setup.py", line 61, in <module>
    shutil.copy( "curated_alignments/germlines.py", ANARCI_LOC )
  File "/usr/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'curated_alignments/germlines.py'`

tried to run a example anyway:

`root@a7c20636b99b:/ANARCI# ANARCI -i Example_sequence_files/12e8.fasta
Error:  Unknown amino acid letter found in sequence: 1, /, U, 2, ., 8, _, X
root@a7c20636b99b:/ANARCI# cd Example_scripts_and_sequences/
root@a7c20636b99b:/ANARCI/Example_scripts_and_sequences# ANARCI -i 12e8.fasta
Error:  b'\nError: File existence/permissions problem in trying to open HMM file /usr/local/lib/python3.8/dist-packages/anarci/dat/HMMs/ALL.hmm.\nHMM file /usr/local/lib/python3.8/dist-packages/anarci/dat/HMMs/ALL.hmm not found (nor an .h3m binary of it); also looked in PF\n\n'`

So what happens here is, that if I run the command from outside the directory 'Example_scripts_and_files' it breaks with ERROR unknown amino acids, which seems to be from a fasta-reader which takes also the path of the file not only the name of the file or something. 

When running the command from whitin the folder there is the actual ERROR which says that there are no hmms in installation-path. Somehow it seems the installation doesnt copy the files from "./ANARCI/lib/python/anarci/dat/HMMs/ALL.hmm" to "/usr/local/lib/python3.8/dist-packages/anarci/dat/HMMs/ALL.hmm".

Hope this gives someone an idea what might be the issue. And I hope someone could help me get ANARCI running in a docker-image.

**Comment by anishazaveri** [comment]
Same error. I used the docker image of ANARCI instead `docker pull quay.io/biocontainers/anarci:2020.04.23--py_3`

**Comment by DewBudd** [comment]
Going off of @awesome-crab's troubleshooting, this minimal Dockerfile creates a functioning ANARCI that can be run from any folder in the container. Including the `python setup.py install` was messing everything up. The `mkdir` and `cp`'s get around having to use it.

```
FROM rocker/shiny-verse
RUN apt update && apt install -y \
  hmmer \
  git \
  python3 \
  python3-pip \
  && rm -r /var/lib/apt/lists/* \
  && pip install biopython \
  && git clone https://github.com/oxpig/ANARCI.git \
  && mkdir -p /usr/local/lib/python3.8/dist-packages/anarci \
  && cp -r /ANARCI/lib/python/anarci/* /usr/local/lib/python3.8/dist-packages/anarci
ENV PATH="${PATH}:/ANARCI/bin"
```

**Comment by merkys** [comment]
Uncommenting the following lines in `setup.py` makes `python setup.py install` install the data files in their intended location:
https://github.com/oxpig/ANARCI/blob/c2fd0f75ee3aa4cff842548d3d75b64815a8f663/setup.py#L23-L27

**Comment by awesome-crab** [comment]
> Uncommenting the following lines in `setup.py` makes `python setup.py install` install the data files in their intended location:
> 
> https://github.com/oxpig/ANARCI/blob/c2fd0f75ee3aa4cff842548d3d75b64815a8f663/setup.py#L23-L27

Just tested this and the error is still:

Traceback (most recent call last):
  File "setup.py", line 61, in <module>
    shutil.copy( "curated_alignments/germlines.py", ANARCI_LOC )
  File "/usr/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'curated_alignments/germlines.py'

And the setup.py file is:

root@fb0e07de9017:/ANARCI# more setup.py

setup(name='anarci',
      version='1.3',
      description='Antibody Numbering and Receptor ClassIfication',
      author='James Dunbar',
      author_email='opig@stats.ox.ac.uk',
      url='http://opig.stats.ox.ac.uk/webapps/ANARCI',
      packages=['anarci'],
      package_dir={'anarci': 'lib/python/anarci'},
      package_data={'anarci': ['dat/HMMs/ALL.hmm',
                               'dat/HMMs/ALL.hmm.h3f',
                               'dat/HMMs/ALL.hmm.h3i',
                               'dat/HMMs/ALL.hmm.h3m',
                               'dat/HMMs/ALL.hmm.h3p']},
      scripts=['bin/ANARCI'],
      data_files = [ ('bin', ['bin/muscle', 'bin/muscle_macOS']) ]
     )

**Comment by awesome-crab** [comment]
> > Traceback (most recent call last):
> > File "setup.py", line 61, in
> > shutil.copy( "curated_alignments/germlines.py", ANARCI_LOC )
> > File "/usr/lib/python3.8/shutil.py", line 418, in copy
> > copyfile(src, dst, follow_symlinks=follow_symlinks)
> > File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
> > with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
> > FileNotFoundError: [Errno 2] No such file or directory: 'curated_alignments/germlines.py'
> 
> Right, I was using `pip install .`, not `python setup.py install`. `pip install .` seems to circumvent `build` stage, which is causing the failure in your case.

Wow. Thanks for the hint!! I was naively following the installation instructions. But just using `pip install .` seems to work fine. Even with commented lines 23 - 27.

**Comment by merkys** [comment]
> Wow. Thanks for the hint!! I was naively following the installation instructions. But just using `pip install .` seems to work fine. Even with commented lines 23 - 27.

Right, but can you confirm ANARCI actually works lines 23-27 commented out? For me any input fails with `File existence/permissions problem in trying to open HMM file /usr/local/lib/python3.8/dist-packages/anarci/dat/HMMs/ALL.hmm` message as HMM files will not get installed when said lines are commented out.

**Comment by awesome-crab** [comment]
Sorry. Contrary to my previous comment it is not working for me. To be clear:

installation with pip install . and uncommented setup.py file does not work.
installation with pip install . and commented setup.py file does not work.

installation with python setup.py install . and uncommented setup.py file does not work.
installation with python setup.py install . and commented setup.py file does not work.

**Comment by merkys** [comment]
I see. Are you seeing the same message in all four cases? To me `pip install .` with uncommented lines works. I am using Python 3.10 by the way.

**Comment by awesome-crab** [comment]
`pip install .` with commented setup.py fails the way you describe: `File existence/permissions problem in trying to open HMM file /usr/local/lib/python3.8/dist-packages/anarci/dat/HMMs/ALL.hmm`

The uncommented install attempt works. But running the ANARCI commands only work when the working dir is where the fasta file is.

The other 2 fail as described here https://github.com/oxpig/ANARCI/issues/16#issue-928750246 and here https://github.com/oxpig/ANARCI/issues/16#issuecomment-979318853

**Comment by awesome-crab** [comment]
when I run this command in the folder ANARCI/ : `ANARCI -i Example_sequence_files/12e8.fasta`
it fails with Error: Unknown amino acid letter found in sequence: _, U, 1, 8, 2, X, /, .
when I run the command in ANARCI/Example_sequence_files/ : `ANARCI -i 12e8.fasta` it works
