### ISSUE TITLE
Error: unsupported operand type(s) for +: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by Linun-Van** [oxpig/ANARCI#26]
When I use ANARCI to number antibodies, sometimes this error occurs. 
And this error always appears at the end of the program. 
What should I do?

**Comment by Linun-Van** [comment]
Error:  unsupported operand type(s) for +: 'NoneType' and 'int'
![2021-12-22 14-20-42 的屏幕截图](https://user-images.githubusercontent.com/96514594/147045419-8d22b355-1b19-4a1d-bf89-0ea178f2c6b4.png)

**Comment by Linun-Van** [comment]
The reason for this problem is that some antibody sequences have extremely long CDR3, which leads to errors in initializing the jRegion variable in the check_for_j function in the program.

**Comment by broncio123** [comment]
> When I use ANARCI to number antibodies, sometimes this error occurs. And this error always appears at the end of the program. What should I do?

Hi @Linun-Van 
For us to help you, could you provide us with the 1) command that you executed and 2) the inputs provided?
Take a screenshot or copy and paste the commands here.

**Comment by jeanjvs** [comment]
Hi,
I got the same error a few times. The sequences that we causing this error are on the attached fasta file. They are supposed to be normal IG sequences, but this error happened with all numbering schemes I tried.
This was the command I used:
ANARCI -i error.fasta -s martin

And the output was:
Warning: Non IG chains cannot be numbered with the kabat scheme. These will be ignored.
Error:  unsupported operand type(s) for +: 'NoneType' and 'int'

[error.fasta.txt](https://github.com/oxpig/ANARCI/files/9277161/error.fasta.txt)

**Comment by sysimm** [comment]
I encountered the error as well, using the following command: `ANARCI --sequence error.fa --scheme imgt` with the following stacktrace:
```
Traceback (most recent call last):
  File "/home/project/miniconda3/envs/project/bin/ANARCI", line 187, in <module>
    sequences, numbered, alignment_details, hit_tables =  run_anarci(args.inputsequence, scheme=args.scheme, output=True,
  File "/home/project/miniconda3/envs/project/lib/python3.10/site-packages/anarci/anarci.py", line 931, in run_anarci
    results = list(map( anarci_partial, grouper( chunksize, sequences ) ))
  File "/home/project/miniconda3/envs/project/lib/python3.10/site-packages/anarci/anarci.py", line 834, in anarci
    check_for_j( sequences, alignments, scheme )
  File "/home/project/miniconda3/envs/project/lib/python3.10/site-packages/anarci/anarci.py", line 744, in check_for_j
    jRegion   = [ (state, index+cys_si+1) for state, index in re_states[0] if state[0] >= 117 ]
  File "/home/project/miniconda3/envs/project/lib/python3.10/site-packages/anarci/anarci.py", line 744, in <listcomp>
    jRegion   = [ (state, index+cys_si+1) for state, index in re_states[0] if state[0] >= 117 ]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```
Anarci was installed using `conda install -c bioconda anarci=2021.02.04`
[error.fa.txt](https://github.com/oxpig/ANARCI/files/9347394/error.fa.txt)

**Comment by aybarsnazlica** [comment]
I think the cause of the error is that deletion states that the `run_hmmer()` function returns, have an index of `None`. This is not handled in the code.  It's possible to fix the error by checking that the `index` variable isn’t `None`.  
<img width="1012" alt="Screenshot 2024-01-21 at 12 49 41 PM" src="https://github.com/oxpig/ANARCI/assets/98632300/45109a9d-4ab1-4033-b6c5-0ee008928811">
