### ISSUE TITLE
Using ANARCI through Parapred

### ISSUE THREAD

**Issue by hanzhiz** [oxpig/ANARCI#60]
Hello,

I have a issue with using anarci with through parapred. When importing anarci, cannot import .germlines. Actually in lib there is no germlines.py file. Do you know how to solve it? 

Following is the error command: 

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
/usr/local/lib64/python3.6/site-packages/Bio/SearchIO/__init__.py:211: BiopythonExperimentalWarning: Bio.SearchIO is an experimental submodule which may undergo significant changes prior to its future official release.
  BiopythonExperimentalWarning)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/parapred-1.0.1-py3.6.egg/parapred/full_seq_processor.py", line 32, in get_CDR_simple
  File "/root/.local/lib/python3.6/site-packages/anarci/__init__.py", line 3, in <module>
    from .anarci import *
  File "/root/.local/lib/python3.6/site-packages/anarci/anarci.py", line 68, in <module>
    from .germlines import all_germlines
ModuleNotFoundError: No module named 'anarci.germlines'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/parapred", line 33, in <module>
    sys.exit(load_entry_point('parapred==1.0.1', 'console_scripts', 'parapred')())
  File "/usr/local/lib/python3.6/site-packages/parapred-1.0.1-py3.6.egg/parapred/parapred.py", line 227, in main
  File "/usr/local/lib/python3.6/site-packages/parapred-1.0.1-py3.6.egg/parapred/parapred.py", line 197, in process_full_VH_VL_sequence
  File "/usr/local/lib/python3.6/site-packages/parapred-1.0.1-py3.6.egg/parapred/full_seq_processor.py", line 34, in get_CDR_simple
Exception: 
**ImportError** function get_CDR_simple() requires the python module anarci
 Available from http://opig.stats.ox.ac.uk/webapps/sabdab-sabpred/ANARCI.php

**Comment by FBoyles** [comment]
You need to run the script build_pupeline/RUN_pipeline.sh. This downloads germline data and builds HMM models. This script is run as part of the installation process, so should not be necessary if the package was installed correctly. Closing as not a code issue.
